apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: java-client-library
  title: Java client library template
  description: Java client library, allows creating client given a swagger link.
  tags:
    - recommended
    - swagger
    - java-client
spec:
  owner: Platform Engineering (#rpe)
  templater: cookiecutter
  type: library
  schema:
    required:
      - component_id
      - swagger_path
      - base_package
    properties:
      component_id:
        title: Component name
        type: string
        description: Name of the component, e.g. idam-client-library. This will be used as artifact id.
      description:
        title: Description
        type: string
        description: Description of the library.
      swagger_path:
        title: Path to Swagger
        type: string
        description: Path to Swagger
      base_package:
        title: Base package for client
        type: string
        description: base package for generated classes, example `uk.gov.hmcts.reform.idam.client`