apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: java-client-library
  title: Java client library template
  description: Java client library, allows creating client given a swagger link.
  tags:
    - recommended
    - swagger
    - java-client
spec:
  owner: Platform Engineering (#rpe)
  templater: cookiecutter
  type: library
  schema:
    required:
      - component_id
      - openapi_url
      - base_package
    properties:
      component_id:
        title: Component name
        type: string
        description: Name of the component, e.g. idam-java-client. idam-client will be artifact id in this case.
      description:
        title: Description
        type: string
        description: Description of the library.
      openapi_url:
        title: OpenAPI URL
        type: string
        description: URL for OpenAPI spec, e.g. https://raw.githubusercontent.com/hmcts/reform-api-docs/master/docs/specs/bulk-scan-processor.json
      base_package:
        title: Base package for client
        type: string
        description: base package for generated classes, example `uk.gov.hmcts.reform.idam.client`
